version: '3.4'

x-common:
  volumes: &volumes
    - build:/app/build/
    - .:/app:delegated
    - ./.env.dist:/app/build/.env.dist
    - ./.env:/app/build/.env

services:
  builder:
    volumes: *volumes

  js:
    volumes: *volumes

  boilerplate_api:
    volumes: *volumes
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app

